sudo: required
language: node_js
services:
  - docker
node_js: 5
script:
  - npm run build
deploy:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_UESRNAME" -p="$DOCKER_PASSWORD"
  - docker build -t progre/sutahigashi .
  - docker push progre/sutahigashi
