sudo: required
language: node_js
node_js: 5
services:
  - docker
cache:
  directories:
    - node_modules
script:
  - npm run build
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_UESRNAME" -p="$DOCKER_PASSWORD"
  - docker build -t progre/sutahigashi .
  - docker push progre/sutahigashi
