sudo: required
language: node_js
node_js: 5
services:
  - docker
script:
  - npm run build
  - docker build -t $TRAVIS_REPO_SLUG .
  - docker run -d -p 3000:80 $TRAVIS_REPO_SLUG
  - curl --retry 10 --retry-delay 5 -v http://127.0.0.1:3000
after_success:
  - export product=`test "$TRAVIS_PULL_REQUEST" == false && test "$TRAVIS_BRANCH" == master && echo true`
  - test "$product" == true && docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - test "$product" == true && docker push $TRAVIS_REPO_SLUG
