sudo: required
language: node_js
node_js:
  - 5
services:
  - docker
cache:
  directories:
    - node_modules
script:
  - npm run build
after_script:
  - docker login --email="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t progre/sutahigashi .
  - docker push progre/sutahigashi
