sudo: required
language: node_js
node_js: 5
services:
  - docker
script:
  - npm run build
after_success:
  - export product=`test "$TRAVIS_PULL_REQUEST" == false && test "$TRAVIS_BRANCH" == master && echo true`
  - test "$product" == true && docker login --email="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t $TRAVIS_REPO_SLUG .
  - test "$product" == true && docker push $TRAVIS_REPO_SLUG
